name: GitHub Actions Demo
on: 
  push:
    branches:
      - 'develop'
jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
        S3_CONFIG: ${{ secrets.S3_CONFIG }}
      - run: echo $S3_CONFIG | base64 -d


