name: GitHub Actions Demo
on: 
  push:
    branches:
      - 'develop'
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      env:
      S3_CONFIG: ${{ secrets.S3_CONFIG }}
      - run: echo $S3_CONFIG | base64 -d


